Add service init, bunle command

diff --git a/proton-cdk b/proton-cdk
--- a/proton-cdk
+++ b/proton-cdk
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.2 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.0 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -71,8 +71,8 @@ proton_cdk_service_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   make directory structure\n" "create"
-  printf "  %s   make bundle.\n" "build "
+  printf "  %s   make directory structure and templates.\n" "init  "
+  printf "  %s   make bundle.\n" "bundle"
   echo
 
   # :command.long_usage
@@ -88,25 +88,39 @@ proton_cdk_service_usage() {
 }
 
 # :command.usage
-proton_cdk_service_create_usage() {
+proton_cdk_service_init_usage() {
   if [[ -n $long_usage ]]; then
-    printf "proton-cdk service create - make directory structure\n"
+    printf "proton-cdk service init\n"
+    echo
+
+    printf "  make directory structure and templates.\n  1) Not specified --major\n  \$name/instance_infrastructure\n  \n  2) Specified --major 1\n  \$name/v1/instance_infrastructure\n"
     echo
 
   else
-    printf "proton-cdk service create - make directory structure\n"
+    printf "proton-cdk service init - make directory structure and templates.\n"
     echo
 
   fi
 
   printf "%s\n" "Usage:"
-  printf "  proton-cdk service create [NAME]\n"
-  printf "  proton-cdk service create --help | -h\n"
+  printf "  proton-cdk service init [NAME] [OPTIONS]\n"
+  printf "  proton-cdk service init --help | -h\n"
   echo
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--target, -t TARGET (required)"
+    printf "    target_name:version\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--major, -m MAJOR_VERSION"
+    printf "    major-version of service template.\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
@@ -125,20 +139,20 @@ proton_cdk_service_create_usage() {
 }
 
 # :command.usage
-proton_cdk_service_build_usage() {
+proton_cdk_service_bundle_usage() {
   if [[ -n $long_usage ]]; then
-    printf "proton-cdk service build - make bundle.\n"
+    printf "proton-cdk service bundle - make bundle.\n"
     echo
 
   else
-    printf "proton-cdk service build - make bundle.\n"
+    printf "proton-cdk service bundle - make bundle.\n"
     echo
 
   fi
 
   printf "%s\n" "Usage:"
-  printf "  proton-cdk service build\n"
-  printf "  proton-cdk service build --help | -h\n"
+  printf "  proton-cdk service bundle\n"
+  printf "  proton-cdk service bundle --help | -h\n"
   echo
 
   # :command.long_usage
@@ -341,6 +355,22 @@ customize_environment_cdk_json() {
   mv -f tmp2.json cdk.json
 }
 
+customize_service_tsconfig_json() {
+  jq '.compilerOptions.resolveJsonModule=true | .compilerOptions.esModuleInterop=true' tsconfig.json > tmp3.json
+  mv -f tmp3.json tsconfig.json
+}
+
+customize_service_package_json() {
+  local major=${1:-1}
+  jq --arg major "$major" '.version="\($major).0.0"' package.json > tmp1.json
+  mv -f tmp1.json package.json
+}
+
+customize_service_cdk_json() {
+  jq '.outputsFile="cdk-outputs.json" | .requireApproval="never"' cdk.json > tmp2.json
+  mv -f tmp2.json cdk.json
+}
+
 # src/lib/proton_templates.sh
 create_cdk_to_proton_sh () {
   cat << BASH > cdk-to-proton.sh
@@ -354,7 +384,36 @@ BASH
   chmod 755 cdk-to-proton.sh
 }
 
+create_template_registration () {
+  local target="$1"
+  cat << YAML > .template-registration
+compatible_environments:
+  - $target
+YAML
+}
+
 create_environment_schema () {
+  cat << YAML > schema.yaml
+schema:
+  format:
+    openapi: "3.0.0"
+  environment_input_type: "EnvironmentInputs"
+  types:
+    EnvironmentInputs:
+      type: object
+      description: "Input properties for my environment"
+      properties:
+        vpc_cidr_block:
+          type: string
+          title: "VPC CIDR block"
+          description: "VPC CIDR block, or default if left blank"
+          default: "10.0.0.0/16"
+      required:
+        - vpc_cidr_block
+YAML
+}
+
+create_service_schema () {
   cat << YAML > schema.yaml
 schema:
   format:
@@ -381,9 +440,35 @@ infrastructure:
   templates:
     - rendering_engine: codebuild
       settings:
-        image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
+        image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
         runtimes:
-          nodejs: 16
+          nodejs: 18
+        provision:
+          # Run when create/update is triggered for environment or service
+          # Install dependencies
+          - npm install
+          - npm run cdk -- deploy
+          # Script to convert CDK outputs into outputs for Proton
+          - chmod +x ./cdk-to-proton.sh
+          - cat cdk-outputs.json | ./cdk-to-proton.sh > proton-outputs.json
+          # Notify AWS Proton of deployment status
+          - aws proton notify-resource-deployment-status-change --resource-arn $RESOURCE_ARN --outputs file://./proton-outputs.json
+        deprovision:
+          # Install dependencies and destroy resources
+          - npm install
+          - npm run cdk -- destroy --force
+YAML
+}
+
+create_service_manifest_yaml() {
+cat << YAML > manifest.yaml
+infrastructure:
+  templates:
+    - rendering_engine: codebuild
+      settings:
+        image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
+        runtimes:
+          nodejs: 18
         provision:
           # Run when create/update is triggered for environment or service
           # Install dependencies
@@ -404,22 +489,52 @@ YAML
 # :command.command_functions
 
 # :command.function
-proton_cdk_service_create_command() {
-  # src/service_create_command.sh
-  echo "# this file is located in 'src/service_create_command.sh'"
-  echo "# code for 'proton-cdk service create' goes here"
-  echo "# you can edit it freely and regenerate (it will not be overwritten)"
-  inspect_args
+proton_cdk_service_init_command() {
+  # src/service_init_command.sh
+  local name="${args[name]}"
+  local major="${args[--major]}"
+  local target="${args[--target]}"
+
+  local tmpdir="$(mktemp -d)"
+  mkdir -p "$tmpdir/$name"
+
+  pushd "$tmpdir/$name" >/dev/null
+    npx cdk init app --language=typescript --generate-only
+    create_template_registration "$target"
+    create_service_manifest_yaml
+    create_cdk_to_proton_sh
+    customize_service_package_json "$major"
+    customize_service_cdk_json
+    customize_service_tsconfig_json
+  popd >/dev/null
+
+  if [ -z "$major" ]; then
+    mkdir -p "$name/schema"
+    pushd "$name/schema" >/dev/null
+      create_service_schema
+    popd >/dev/null
+    mv "$tmpdir/$name" "$name/instance_infrastructure"
+  else
+    mkdir -p "$name/v$major/schema"
+    pushd "$name/v$major/schema" >/dev/null
+      create_service_schema
+    popd >/dev/null
+    mv "$tmpdir/$name" "$name/v$major/instance_infrastructure"
+  fi
+
+  rmdir $tmpdir
 
 }
 
 # :command.function
-proton_cdk_service_build_command() {
-  # src/service_build_command.sh
-  echo "# this file is located in 'src/service_build_command.sh'"
-  echo "# code for 'proton-cdk service build' goes here"
-  echo "# you can edit it freely and regenerate (it will not be overwritten)"
-  inspect_args
+proton_cdk_service_bundle_command() {
+  # src/service_bundle_command.sh
+  if [ ! -f "instance_infrastructure/package.json" ]; then
+    echo "instance_infrastructure/package.json is not exists."
+    return 1
+  fi
+  local output="$(bundle_filename_from_package_json 'instance_infrastructure/package.json')"
+  find . -mindepth 1 -type f | sed 's/^\.\///' | grep -v node_modules | xargs tar zcf $output
 
 }
 
@@ -575,17 +690,17 @@ proton_cdk_service_parse_requirements() {
   case $action in
     -*) ;;
 
-    create)
-      action="create"
+    init)
+      action="init"
       shift
-      proton_cdk_service_create_parse_requirements "$@"
+      proton_cdk_service_init_parse_requirements "$@"
       shift $#
       ;;
 
-    build)
-      action="build"
+    bundle)
+      action="bundle"
       shift
-      proton_cdk_service_build_parse_requirements "$@"
+      proton_cdk_service_bundle_parse_requirements "$@"
       shift $#
       ;;
 
@@ -626,13 +741,13 @@ proton_cdk_service_parse_requirements() {
 }
 
 # :command.parse_requirements
-proton_cdk_service_create_parse_requirements() {
+proton_cdk_service_init_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
         long_usage=yes
-        proton_cdk_service_create_usage
+        proton_cdk_service_init_usage
         exit
         ;;
 
@@ -644,12 +759,41 @@ proton_cdk_service_create_parse_requirements() {
   done
 
   # :command.command_filter
-  action="service create"
+  action="service init"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+      # :flag.case
+      --target | -t)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--target']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--target requires an argument: --target, -t TARGET" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --major | -m)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--major']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--major requires an argument: --major, -m MAJOR_VERSION" >&2
+          exit 1
+        fi
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -673,16 +817,22 @@ proton_cdk_service_create_parse_requirements() {
     esac
   done
 
+  # :command.required_flags_filter
+  if [[ -z ${args['--target']+x} ]]; then
+    printf "missing required flag: --target, -t TARGET\n" >&2
+    exit 1
+  fi
+
 }
 
 # :command.parse_requirements
-proton_cdk_service_build_parse_requirements() {
+proton_cdk_service_bundle_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
         long_usage=yes
-        proton_cdk_service_build_usage
+        proton_cdk_service_bundle_usage
         exit
         ;;
 
@@ -694,7 +844,7 @@ proton_cdk_service_build_parse_requirements() {
   done
 
   # :command.command_filter
-  action="service build"
+  action="service bundle"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -922,8 +1072,8 @@ run() {
 
   case "$action" in
     "service") proton_cdk_service_command ;;
-    "service create") proton_cdk_service_create_command ;;
-    "service build") proton_cdk_service_build_command ;;
+    "service init") proton_cdk_service_init_command ;;
+    "service bundle") proton_cdk_service_bundle_command ;;
     "environment") proton_cdk_environment_command ;;
     "environment init") proton_cdk_environment_init_command ;;
     "environment bundle") proton_cdk_environment_bundle_command ;;
